name: Build AndUEDumper

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c

    - name: Build with ndk-build
      run: |
        cd AndUEDumper
        ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk

    - name: Upload built binary
      uses: actions/upload-artifact@v4
      with:
        name: AndUEDumper-ARM64
        path: AndUEDumper/libs/arm64-v8a/AndUEDumper
